ORIGINAL_COLUMNS = [
    'Article DOI',
    'Authors',
    'ZINC ID of Ligand',
    'koff (s-1)',
    'kon (M-1-s-1)',
    'pH',
    'BindingDB Entry DOI',
    'BindingDB Ligand Name',
    'BindingDB MonomerID',
    'BindingDB Reactant_set_id',
    'ChEBI ID of Ligand',
    'ChEMBL ID of Ligand',
    'Curation/DataSource',
    'DrugBank ID of Ligand',
    'EC50 (nM)',
    'IC50 (nM)',
    'IUPHAR_GRAC ID of Ligand',
    'Institution',
    'KEGG ID of Ligand',
    'Kd (nM)',
    'Ki (nM)',
    'Ligand HET ID in PDB',
    'Ligand InChI',
    'Ligand InChI Key',
    'Ligand SMILES',
    'Link to Ligand in BindingDB',
    'Link to Ligand-Target Pair in BindingDB',
    'Link to Target in BindingDB',
    'Number of Protein Chains in Target (>1 implies a multichain complex)',
    'PDB ID(s) for Ligand-Target Complex',
    'PMID',
    'Patent Number',
    'PubChem AID',
    'PubChem CID',
    'PubChem SID',
    'Target Name',
    'Target Source Organism According to Curator or DataSource',
    'Temp (C)',
    'BindingDB Target Chain Sequence',
    'BindingDB Target Chain Sequence.1',
    'BindingDB Target Chain Sequence.2',
    'BindingDB Target Chain Sequence.3',
    'BindingDB Target Chain Sequence.4',
    'BindingDB Target Chain Sequence.5',
    'BindingDB Target Chain Sequence.6',
    'BindingDB Target Chain Sequence.7',
    'BindingDB Target Chain Sequence.8',
    'BindingDB Target Chain Sequence.9',
    'BindingDB Target Chain Sequence.10',
    'BindingDB Target Chain Sequence.11',
    'BindingDB Target Chain Sequence.12',
    'PDB ID(s) of Target Chain',
    'PDB ID(s) of Target Chain.1',
    'PDB ID(s) of Target Chain.2',
    'PDB ID(s) of Target Chain.3',
    'PDB ID(s) of Target Chain.4',
    'PDB ID(s) of Target Chain.5',
    'PDB ID(s) of Target Chain.6',
    'PDB ID(s) of Target Chain.7',
    'PDB ID(s) of Target Chain.8',
    'PDB ID(s) of Target Chain.9',
    'PDB ID(s) of Target Chain.10',
    'PDB ID(s) of Target Chain.11',
    'PDB ID(s) of Target Chain.12',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.1',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.2',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.3',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.4',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.5',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.6',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.7',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.8',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.9',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.10',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.11',
    'UniProt (SwissProt) Alternative ID(s) of Target Chain.12',
    'UniProt (SwissProt) Entry Name of Target Chain',
    'UniProt (SwissProt) Entry Name of Target Chain.1',
    'UniProt (SwissProt) Entry Name of Target Chain.2',
    'UniProt (SwissProt) Entry Name of Target Chain.3',
    'UniProt (SwissProt) Entry Name of Target Chain.4',
    'UniProt (SwissProt) Entry Name of Target Chain.5',
    'UniProt (SwissProt) Entry Name of Target Chain.6',
    'UniProt (SwissProt) Entry Name of Target Chain.7',
    'UniProt (SwissProt) Entry Name of Target Chain.8',
    'UniProt (SwissProt) Entry Name of Target Chain.9',
    'UniProt (SwissProt) Entry Name of Target Chain.10',
    'UniProt (SwissProt) Entry Name of Target Chain.11',
    'UniProt (SwissProt) Entry Name of Target Chain.12',
    'UniProt (SwissProt) Primary ID of Target Chain',
    'UniProt (SwissProt) Primary ID of Target Chain.1',
    'UniProt (SwissProt) Primary ID of Target Chain.2',
    'UniProt (SwissProt) Primary ID of Target Chain.3',
    'UniProt (SwissProt) Primary ID of Target Chain.4',
    'UniProt (SwissProt) Primary ID of Target Chain.5',
    'UniProt (SwissProt) Primary ID of Target Chain.6',
    'UniProt (SwissProt) Primary ID of Target Chain.7',
    'UniProt (SwissProt) Primary ID of Target Chain.8',
    'UniProt (SwissProt) Primary ID of Target Chain.9',
    'UniProt (SwissProt) Primary ID of Target Chain.10',
    'UniProt (SwissProt) Primary ID of Target Chain.11',
    'UniProt (SwissProt) Primary ID of Target Chain.12',
    'UniProt (SwissProt) Recommended Name of Target Chain',
    'UniProt (SwissProt) Recommended Name of Target Chain.1',
    'UniProt (SwissProt) Recommended Name of Target Chain.2',
    'UniProt (SwissProt) Recommended Name of Target Chain.3',
    'UniProt (SwissProt) Recommended Name of Target Chain.4',
    'UniProt (SwissProt) Recommended Name of Target Chain.5',
    'UniProt (SwissProt) Recommended Name of Target Chain.6',
    'UniProt (SwissProt) Recommended Name of Target Chain.7',
    'UniProt (SwissProt) Recommended Name of Target Chain.8',
    'UniProt (SwissProt) Recommended Name of Target Chain.9',
    'UniProt (SwissProt) Recommended Name of Target Chain.10',
    'UniProt (SwissProt) Recommended Name of Target Chain.11',
    'UniProt (SwissProt) Recommended Name of Target Chain.12',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.1',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.2',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.3',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.4',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.5',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.6',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.7',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.8',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.9',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.10',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.11',
    'UniProt (SwissProt) Secondary ID(s) of Target Chain.12',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.1',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.2',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.3',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.4',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.5',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.6',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.7',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.8',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.9',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.10',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.11',
    'UniProt (TrEMBL) Alternative ID(s) of Target Chain.12',
    'UniProt (TrEMBL) Entry Name of Target Chain',
    'UniProt (TrEMBL) Entry Name of Target Chain.1',
    'UniProt (TrEMBL) Entry Name of Target Chain.2',
    'UniProt (TrEMBL) Entry Name of Target Chain.3',
    'UniProt (TrEMBL) Entry Name of Target Chain.4',
    'UniProt (TrEMBL) Entry Name of Target Chain.5',
    'UniProt (TrEMBL) Entry Name of Target Chain.6',
    'UniProt (TrEMBL) Entry Name of Target Chain.7',
    'UniProt (TrEMBL) Entry Name of Target Chain.8',
    'UniProt (TrEMBL) Entry Name of Target Chain.9',
    'UniProt (TrEMBL) Entry Name of Target Chain.10',
    'UniProt (TrEMBL) Entry Name of Target Chain.11',
    'UniProt (TrEMBL) Entry Name of Target Chain.12',
    'UniProt (TrEMBL) Primary ID of Target Chain',
    'UniProt (TrEMBL) Primary ID of Target Chain.1',
    'UniProt (TrEMBL) Primary ID of Target Chain.2',
    'UniProt (TrEMBL) Primary ID of Target Chain.3',
    'UniProt (TrEMBL) Primary ID of Target Chain.4',
    'UniProt (TrEMBL) Primary ID of Target Chain.5',
    'UniProt (TrEMBL) Primary ID of Target Chain.6',
    'UniProt (TrEMBL) Primary ID of Target Chain.7',
    'UniProt (TrEMBL) Primary ID of Target Chain.8',
    'UniProt (TrEMBL) Primary ID of Target Chain.9',
    'UniProt (TrEMBL) Primary ID of Target Chain.10',
    'UniProt (TrEMBL) Primary ID of Target Chain.11',
    'UniProt (TrEMBL) Primary ID of Target Chain.12',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.1',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.2',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.3',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.4',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.5',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.6',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.7',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.8',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.9',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.10',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.11',
    'UniProt (TrEMBL) Secondary ID(s) of Target Chain.12',
    'UniProt (TrEMBL) Submitted Name of Target Chain',
    'UniProt (TrEMBL) Submitted Name of Target Chain.1',
    'UniProt (TrEMBL) Submitted Name of Target Chain.2',
    'UniProt (TrEMBL) Submitted Name of Target Chain.3',
    'UniProt (TrEMBL) Submitted Name of Target Chain.4',
    'UniProt (TrEMBL) Submitted Name of Target Chain.5',
    'UniProt (TrEMBL) Submitted Name of Target Chain.6',
    'UniProt (TrEMBL) Submitted Name of Target Chain.7',
    'UniProt (TrEMBL) Submitted Name of Target Chain.8',
    'UniProt (TrEMBL) Submitted Name of Target Chain.9',
    'UniProt (TrEMBL) Submitted Name of Target Chain.10',
    'UniProt (TrEMBL) Submitted Name of Target Chain.11',
    'UniProt (TrEMBL) Submitted Name of Target Chain.12'
]


NORMALIZED_COLUMNS = [
    'Article_DOI',
    'Authors',
    'ZINC_ID_of_Ligand',
    'koff_s-1',
    'kon_M-1-s-1',
    'pH',
    'BindingDB_Entry_DOI',
    'BindingDB_Ligand_Name',
    'BindingDB_MonomerID',
    'BindingDB_Reactant_set_id',
    'ChEBI_ID_of_Ligand',
    'ChEMBL_ID_of_Ligand',
    'Curation_AND_DataSource',
    'DrugBank_ID_of_Ligand',
    'EC50_nM',
    'IC50_nM',
    'IUPHAR_GRAC_ID_of_Ligand',
    'Institution',
    'KEGG_ID_of_Ligand',
    'Kd_nM',
    'Ki_nM',
    'Ligand_HET_ID_in_PDB',
    'Ligand_InChI',
    'Ligand_InChI_Key',
    'Ligand_SMILES',
    'Link_to_Ligand_in_BindingDB',
    'Link_to_Ligand-Target_Pair_in_BindingDB',
    'Link_to_Target_in_BindingDB',
    'Number_of_Protein_Chains_in_Target_>1_implies_a_multichain_complex',
    'PDB_IDs_for_Ligand-Target_Complex',
    'PMID',
    'Patent_Number',
    'PubChem_AID',
    'PubChem_CID',
    'PubChem_SID',
    'Target_Name',
    'Target_Source_Organism_According_to_Curator_or_DataSource',
    'Temp_C',
    'BindingDB_Target_Chain_Sequence',
    'BindingDB_Target_Chain_Sequence_NUMBER_1',
    'BindingDB_Target_Chain_Sequence_NUMBER_2',
    'BindingDB_Target_Chain_Sequence_NUMBER_3',
    'BindingDB_Target_Chain_Sequence_NUMBER_4',
    'BindingDB_Target_Chain_Sequence_NUMBER_5',
    'BindingDB_Target_Chain_Sequence_NUMBER_6',
    'BindingDB_Target_Chain_Sequence_NUMBER_7',
    'BindingDB_Target_Chain_Sequence_NUMBER_8',
    'BindingDB_Target_Chain_Sequence_NUMBER_9',
    'BindingDB_Target_Chain_Sequence_NUMBER_10',
    'BindingDB_Target_Chain_Sequence_NUMBER_11',
    'BindingDB_Target_Chain_Sequence_NUMBER_12',
    'PDB_IDs_of_Target_Chain',
    'PDB_IDs_of_Target_Chain_NUMBER_1',
    'PDB_IDs_of_Target_Chain_NUMBER_2',
    'PDB_IDs_of_Target_Chain_NUMBER_3',
    'PDB_IDs_of_Target_Chain_NUMBER_4',
    'PDB_IDs_of_Target_Chain_NUMBER_5',
    'PDB_IDs_of_Target_Chain_NUMBER_6',
    'PDB_IDs_of_Target_Chain_NUMBER_7',
    'PDB_IDs_of_Target_Chain_NUMBER_8',
    'PDB_IDs_of_Target_Chain_NUMBER_9',
    'PDB_IDs_of_Target_Chain_NUMBER_10',
    'PDB_IDs_of_Target_Chain_NUMBER_11',
    'PDB_IDs_of_Target_Chain_NUMBER_12',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_1',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_2',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_4',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_5',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_6',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_7',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_8',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_9',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_10',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_11',
    'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_12',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_1',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_2',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_4',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_5',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_6',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_7',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_8',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_9',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_10',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_11',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_12',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_1',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_2',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_4',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_5',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_6',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_7',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_8',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_9',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_10',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_11',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_12',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_1',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_2',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_4',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_5',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_6',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_7',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_8',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_9',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_10',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_11',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_12',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_1',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_2',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_4',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_5',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_6',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_7',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_8',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_9',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_10',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_11',
    'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_12',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_1',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_2',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_4',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_5',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_6',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_7',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_8',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_9',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_10',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_11',
    'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_12',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_1',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_2',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_4',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_5',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_6',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_7',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_8',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_9',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_10',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_11',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_12',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_1',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_2',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_4',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_5',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_6',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_7',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_8',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_9',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_10',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_11',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_12',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_1',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_2',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_4',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_5',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_6',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_7',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_8',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_9',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_10',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_11',
    'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_12',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_1',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_2',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_4',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_5',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_6',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_7',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_8',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_9',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_10',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_11',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_12',
]


NORMALIZED_FEAT_COLUMNS = [
    'Article_DOI',
    'Authors',
    'ZINC_ID_of_Ligand',
    'koff_s-1',
    'kon_M-1-s-1',
    'pH',
    'BindingDB_Entry_DOI',
    'BindingDB_Ligand_Name',
    'BindingDB_MonomerID',
    'BindingDB_Reactant_set_id',
    'ChEBI_ID_of_Ligand',
    'ChEMBL_ID_of_Ligand',
    'Curation_AND_DataSource',
    'DrugBank_ID_of_Ligand',
    'EC50_nM',
    'IC50_nM',
    'IUPHAR_GRAC_ID_of_Ligand',
    'Institution',
    'KEGG_ID_of_Ligand',
    'Kd_nM',
    'Ki_nM',
    'Ligand_HET_ID_in_PDB',
    'Ligand_InChI',
    'Ligand_InChI_Key',
    'Ligand_SMILES',
    'Link_to_Ligand_in_BindingDB',
    'Link_to_Ligand-Target_Pair_in_BindingDB',
    'Link_to_Target_in_BindingDB',
    'Number_of_Protein_Chains_in_Target_>1_implies_a_multichain_complex',
    'PDB_IDs_for_Ligand-Target_Complex',
    'PMID',
    'Patent_Number',
    'PubChem_AID',
    'PubChem_CID',
    'PubChem_SID',
    'Target_Name',
    'Target_Source_Organism_According_to_Curator_or_DataSource',
    'Temp_C',
    # 'BindingDB_Target_Chain_Sequence',
    # 'BindingDB_Target_Chain_Sequence_NUMBER_1',
    # 'BindingDB_Target_Chain_Sequence_NUMBER_2',
    # 'BindingDB_Target_Chain_Sequence_NUMBER_3',
    'PDB_IDs_of_Target_Chain',
    # 'PDB_IDs_of_Target_Chain_NUMBER_1',
    # 'PDB_IDs_of_Target_Chain_NUMBER_2',
    # 'PDB_IDs_of_Target_Chain_NUMBER_3',
    # 'UniProt_SwissProt_Alternative_IDs_of_Target_Chain',
    # 'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_1',
    # 'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_2',
    # 'UniProt_SwissProt_Alternative_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Entry_Name_of_Target_Chain',
    # 'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_1',
    # 'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_2',
    # 'UniProt_SwissProt_Entry_Name_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Primary_ID_of_Target_Chain',
    # 'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_1',
    # 'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_2',
    # 'UniProt_SwissProt_Primary_ID_of_Target_Chain_NUMBER_3',
    'UniProt_SwissProt_Recommended_Name_of_Target_Chain',
    # 'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_1',
    # 'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_2',
    # 'UniProt_SwissProt_Recommended_Name_of_Target_Chain_NUMBER_3',
    # 'UniProt_SwissProt_Secondary_IDs_of_Target_Chain',
    # 'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_1',
    # 'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_2',
    # 'UniProt_SwissProt_Secondary_IDs_of_Target_Chain_NUMBER_3',
    # 'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain',
    # 'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_1',
    # 'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_2',
    # 'UniProt_TrEMBL_Alternative_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Entry_Name_of_Target_Chain',
    # 'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_1',
    # 'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_2',
    # 'UniProt_TrEMBL_Entry_Name_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Primary_ID_of_Target_Chain',
    # 'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_1',
    # 'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_2',
    # 'UniProt_TrEMBL_Primary_ID_of_Target_Chain_NUMBER_3',
    # 'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain',
    # 'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_1',
    # 'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_2',
    # 'UniProt_TrEMBL_Secondary_IDs_of_Target_Chain_NUMBER_3',
    'UniProt_TrEMBL_Submitted_Name_of_Target_Chain',
    # 'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_1',
    # 'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_2',
    # 'UniProt_TrEMBL_Submitted_Name_of_Target_Chain_NUMBER_3',
]

